In [143]:
from sklearn import tree
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import seaborn as sns

In [144]:
df = pd.read_csv('./train.csv')

In [145]:
df123 = df[df["OverallQual"].isin([1,2,3])]
df = df[df["OverallQual"].isin([4,5,6])]

- OverallQual
- BsmtQual
- Neighborhood
- 1stFlrSF
- 2ndFlrSF

In [148]:
cols = ["1stFlrSF", "2ndFlrSF", "LotArea", "TotalBsmtSF", "BedroomAbvGr"]

In [149]:
# X = df[["1stFlrSF", "2ndFlrSF", "Neighborhood", "BsmtQual", "OverallQual"]]
X = df[cols]

In [150]:
y = df["SalePrice"]

In [151]:
reg = LinearRegression().fit(X, y)

In [152]:
y_hat = reg.predict(X)

In [153]:
mean_squared_error(y, y_hat)

649464887.3598176

In [ ]:
672205948.3940336

In [ ]:
649464887.3598176

In [154]:
X123 = df123[cols]
y123 = df123["SalePrice"]
reg123 = LinearRegression().fit(X123, y123)
y123_hat = reg123.predict(X123)
mean_squared_error(y123, y123_hat)

236786427.26620555

In [112]:
260593533.99564606

In [113]:
y[0:10]

1     181500
5     143000
9     118000
10    129500
12    144000
14    157000
16    149000
17     90000
18    159000
19    139000
Name: SalePrice, dtype: int64

In [114]:
y_hat[0:10]

array([150304.36150847, 143309.72176404, 131496.67296192, 134208.48821455,
       125499.76401642, 150500.64861805, 131450.60688408, 108253.10533223,
       141621.77991375, 144002.3468761 ])

In [115]:
y - y_hat

1       31195.638492
5        -309.721764
9      -13496.672962
10      -4708.488215
12      18500.235984
            ...     
1453   -61515.465879
1455    17851.364575
1456    13161.625631
1458     5979.069854
1459    -2567.999661
Name: SalePrice, Length: 887, dtype: float64

In [78]:
np.average((y - y_hat) * (y - y_hat))

2420913519.9640913

In [116]:
2420913519.9640913 - 672205948.3940336

1748707571.5700579

In [79]:
reg.coef_

array([80.17619296, 83.90284572,  0.22090919, 66.46712149])

In [80]:
reg.intercept_

-14014.998904219596

In [81]:
from sklearn.preprocessing import Normalizer

In [82]:
transformer = Normalizer().fit(X)

In [83]:
Xt = transformer.transform(X)

In [84]:
Xt

array([[0.09977985, 0.09954672, 0.98497635, 0.09977985],
       [0.12924381, 0.        , 0.98315415, 0.12924381],
       [0.08099983, 0.0762455 , 0.99048709, 0.08099983],
       ...,
       [0.12823713, 0.12435116, 0.97602706, 0.12435116],
       [0.10959889, 0.        , 0.98791506, 0.10959889],
       [0.12442412, 0.        , 0.98439691, 0.12442412]])

In [85]:
regt = LinearRegression().fit(Xt, y)

In [86]:
yt_hat = regt.predict(Xt)

In [87]:
mean_squared_error(y, yt_hat)

5941700415.764342

In [88]:
y - yt_hat

0       12782.193321
1       -6443.119082
2       35858.244092
3      -40701.693996
4       63198.547443
            ...     
1455   -24277.392839
1456    39457.785349
1457    64566.892328
1458   -41338.805794
1459   -39449.276094
Name: SalePrice, Length: 1460, dtype: float64

In [89]:
regt.coef_

array([-167342.7190313 ,  220744.56535392, 1406740.40927814,
        736277.85130329])

In [90]:
regt.intercept_

-1268630.8901658638

In [132]:
df = pd.get_dummies(df, columns=['Neighborhood'])

In [135]:
X = df[cols]
y = df["SalePrice"]
reg = LinearRegression().fit(X, y)
y_hat = reg.predict(X)
mean_squared_error(y, y_hat)

672205948.3940336

# not helping

In [140]:
df['OverallQual'].unique()

array([6, 5, 4])

In [156]:
reg.score(X, y)

0.5104386792083498

In [158]:
np.average((y - y_hat) * (y - y_hat))

649464887.3598176

In [159]:
np.average(y - np.average(y))

-1.0499690807389836e-12

In [163]:
np.var(y)

1326626225.923226

In [165]:
1 - (np.average((y - y_hat) * (y - y_hat)) / np.var(y))

0.5104386792083491